// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xazhfwmspuhkcmorvunw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhemhmd21zcHVoa2Ntb3J2dW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjYyMzksImV4cCI6MjA2NjU0MjIzOX0.-HlnCni_6C9GEtpSukzs1OcYyBDPfXZ71Ho2kRoIlVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);